adding a dockerfile for aws batch
OrnaComputationTeam/SPOT-RNA-2D pull request #1
Opened 2023-06-15 14:22 UTC by ramindehghanpoor

2023-06-20 19:10 UTC, shivashankarv requested changes
Few minor comments and suggestions. Will approve if urgent.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +# Use a Python base image with the desired version
I'm wondering if we should just use our base Dockerfile located in CodeCommit?

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +# Use a Python base image with the desired version
That already has mamba, ubuntu etc.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +RUN apt-get update --fix-missing -y && \
You might not need all this.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +# Use a Python base image with the desired version
Just use the template here maybe: https://github.com/OrnaComputationTeam/mires/blob/main/Dockerfile.mljar
Can be part of a separate issue.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +RUN mkdir -p /tmp/conda-build && wget -nv https://repo.anaconda.com/miniconda/Miniconda3-py39_23.3.1-0-Linux-x86_64.sh && bash Miniconda3-py39_23.3.1-0-Linux-x86_64.sh -b -p /miniconda3
All of this is there in the image above.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +RUN mamba install -y -c bioconda viennarna infernal easel
We should have version numbers here.

2023-06-20 19:10 UTC, shivashankarv commented on Dockerfile
> +RUN git clone https://github.com/debbiemarkslab/plmc && cd plmc && make all-openmp && cd -
`plmc` is available through conda: https://bioconda.github.io/recipes/plmc/README.html

2023-06-20 19:10 UTC, shivashankarv commented on run_rnacmap.sh
> +# Start measuring the time
If need be you can use a `bash` trap here: https://www.notion.so/ornatx/How-to-create-an-EC2-instance-de8df2c7c6054629bdb0fe8d4b04fce7?pvs=4#d39937e26d6c403cb7b24823b7746b97

2023-06-20 19:10 UTC, shivashankarv commented on run_rnacmap.sh
Could you add a #usage comment here. ie on how to run the shell script.

2023-06-20 19:23 UTC, ramindehghanpoor commented on run_rnacmap.sh
> +# Start measuring the time
Why do we need `bash` trap here? We want to use this shell script in AWS batch.

2023-06-21 15:00 UTC, ramindehghanpoor commented on Dockerfile
> +RUN mamba install -y -c bioconda viennarna infernal easel
As you suggested, I'll use the spec-file instead, so it has the version numbers.

2023-06-21 15:25 UTC, ramindehghanpoor reviewed
@shivashankarv, I made your requested changes. It's ready for your review.

2023-06-23 02:06 UTC, shivashankarv approved these changes

2023-06-23 02:06 UTC, merged